FROM ghcr.io/mcsmanager/mcsmanager-daemon:latest
COPY --link mcsm/bootstrap.cjs /opt/mcnet/bootstrap.cjs
COPY --link mcsm/control.cjs /opt/mcnet/control.cjs
CMD ["node", "/opt/mcnet/bootstrap.cjs", "daemon"]
